micronaut:
  security:
    authentication: session
---
micronaut:
  application:
    name: micronaut
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    packages-to-scan:
      - 'example.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true